# Site settings
title: YangShuailing
email: yangsl1008@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Kevin Law 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/YangShuailing" # the base hostname & protocol for your site
 
github_username: YangShuailing
permalink: /blog/:title

markdown: redcarpet
